use_frameworks!

platform :ios, '8.0'

target 'KLUIViewControllerTranstion_Example' do
  pod 'KLUIViewControllerTranstion', :path => '../'

  target 'KLUIViewControllerTranstion_Tests' do
    inherit! :search_paths

    
  end
end
